import { freeze } from "./formatHelper";

const data = [
	"Acho o silêncio tão tranquilizante... é ótimo para escrever",
	"Me pergunto se a mãe está bem...",
	"Gosto do som da chuva...",
	"Odeio os sons lá de fora... às vezes acho que vou enlouquecer...",
	"Carlos ainda deve estar no exterior... sempre foi meu irmão mais inteligente...",
	"Sinto cheiro de café... ou será chá de camomila...?",
	"Não gosto de doces, mas gostaria de ter um pedaço da torta de chocolate da dona Maria",
	"Quando será que vai acabar?",
	"“Plutão começou a experimentar os efeitos do meu mau temperamento”",
	"Minha cabeça dói...",
	"Espero conseguir publicar meu livro...",
	"Gosto de música!",
	"Às vezes me lembro da época que jogava bola com o Pedro e com o Thiago...",
	"Me pergunto onde os moleques estão...",
	"Estou com fome",
	"Preciso limpar a casa...",
	"Preciso arrumar a cama...",
	"Preciso pegar um copo d’água",
	"Não gosto de exercícios...",
	"Quando tudo acabar vou ir ao teatro",
	"Quando tudo acabar vou ir ao cinema",
	"Quando tudo acabar vou ir ao museu",
	"Quando tudo acabar vou ir visitar minha família",
	"Gosto de gatos",
	"Às vezes o silêncio é ensurdecedor...",
	"Admito que a solidão às vezes é deprimente...",
	"Será que alguém vai gostar do meu livro...?",
	"Sukuna ou Saitama? Quem será que venceria?",
	"Meu livro está ficando tão legal!",
	"Como será que está Marlene e as crianças?",
	"Como será que Roberto está lidando com tudo isso?",
	"Gostaria de estar na cama agora, mas não posso recair...",
	"Espero que tudo acabe bem...",
	"Espero que tudo acabe logo...",
	"Estou feliz hoje!",
	"Não sei se estou bem...",
	"Tive uma ótima ideia para colocar no meu livro!",
	"Se tudo der certo, pretendo viajar ano que vem!",
	"Todos sempre me disseram que eu seria um ótimo jornalista...",
	"Espero que não cheguem a esse fim de mundo",
	"Às vezes juro que os sons estão chegando mais perto...",
	"Aquilo lá fora foi um grito?",
	"Constantemente me sinto observado...",
	"Sempre gostei da solidão, mas agora prefiro estar junto de alguém",
	"Gostaria de comer algo diferente...",
	"Gostaria que pudesse me entreter de mais alguma forma",
	"Estou com uma vontade ilógica e incessante de rir!",
	"Estou com calor!",
	"Estou com frio!",
	"Estou satisfeito!",
];

const thoughts = freeze.array(data, false);

export { thoughts };
